version: '3.1'

services:

  database:
    container_name: finances-database
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: finances_password
      POSTGRES_USER: finances_user
      POSTGRES_DB: finances
    volumes:
      - postgres_finances_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    container_name: database_adminer
    image: adminer
    ports:
      - "80:8080"

volumes:
  postgres_finances_db: