server:
  compression:
    enabled: true

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE_NAME:finances}
    username: ${POSTGRES_USERNAME:finances_user}
    password: ${POSTGRES_PASSWORD:finances_password}
  jpa:
    show-sql: ${SHOW_SQL:true}
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true


springdoc:
  api-docs:
    path: /documentation-api
  swagger-ui:
    path: /documentation
    display-request-duration: true
    display-query-params: true
  remove-broken-reference-definitions: true