spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

springdoc:
  api-docs:
    path: /documentation-api
  swagger-ui:
    path: /documentation
    display-request-duration: true
    display-query-params: true
  remove-broken-reference-definitions: true